services:
  app:
    image: node:23-alpine
    container_name: tech-challenge-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/tech_challenge
    ports:
      - 3001:3000
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    command: sh -c "npm install && npm run start"

  mongo:
    image: mongo:7
    container_name: tech-challenge-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tech_challenge
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:


